# 配置文件版本
# Config file version
config_version: 1.1

# 语言
# Language
language: zh_cn

# 未加载材质包的玩家被踢出时的提示信息
# Message when a player is kicked out because of not loading the material package
message: '您需要安装服务器材质包才能进入服务器!'

# 是否启用发送材质包功能
# Enable sending resourcepack
enable_send_resourcepack: false

# 材质包下载链接
# Material package download link
url: "https://www.google.com/minecraft.zip"

# 材质包 SHA-1 值, 懒得算可留空，程序将自动生成一个随机的 SHA-1 （但会浪费下载服务器带宽）
# Resource pack SHA-1 value, leave it blank and the program will generate a random SHA-1 (but it will waste download server bandwidth)
sha1: ""