name: MeowResources
version: 1.2
main: com.meow.meowresources.MeowResources
api-version: 1.17
softdepend: ["ItemsAdder"]
commands:
  meowresources:
    description: 主插件命令
    usage: /meowresources reload
    subcommands:
      reload:
        description: 重新加载插件配置
        usage: /meowresources reload
permissions:
  meowresources.reload:
    description: 允许重载配置文件
    default: op
